/**
 * `game/buildPositions.js`'s `computePositions()` — the PWA's own equivalent
 * of `samples/build_positions.py`, exercised two ways: against small, worked
 * examples anyone can check by hand, and as a full cross-check against the
 * Python script's own output for the exact same 40-game corpus, so the two
 * independent implementations of §6 are verified to agree rather than
 * assumed to.
 *
 * `tests/fixtures/positions-sample-games.json` was generated by running
 * `samples/build_positions.py sample-games.db` (against the 21 Sep sample
 * corpus, the same one `mock-data/sample-games.js`'s `GAMES` carries) and
 * dumping its `positions` table. Regenerate it the same way if the sample
 * corpus is ever rebuilt.
 */

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { computePositions } from '../src/lib/game/buildPositions.js';
import { GAMES } from '../src/lib/mock-data/sample-games.js';

const here = dirname(fileURLToPath(import.meta.url));
const pythonRows = JSON.parse(readFileSync(resolve(here, 'fixtures/positions-sample-games.json'), 'utf8'));

const sortKey = (r) => `${r.pos}\u0000${r.move}`;
const sorted = (rows) => [...rows].sort((a, b) => (sortKey(a) < sortKey(b) ? -1 : 1));

describe('computePositions — worked examples', () => {
  it('a two-game, hand-checkable corpus: one draw, one decisive, a shared opening', () => {
    const games = [
      {
        id: 901, result: '1-0', movetext: null,
        pgn: '[Result "1-0"]\n\n1. e4 e5 2. Nf3 Nc6 1-0'
      },
      {
        id: 902, result: '1/2-1/2', movetext: null,
        pgn: '[Result "1/2-1/2"]\n\n1. e4 c5 1/2-1/2'
      }
    ];
    const rows = computePositions(games);
    const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -';

    // Both games open 1.e4 — one row, credited to both games.
    const e4 = rows.find((r) => r.pos === START && r.move === 'e4');
    expect(e4).toEqual({ pos: START, move: 'e4', games: 2, white: 1, draws: 1, black: 0 });

    // No other move was ever played from the starting position in this corpus.
    expect(rows.filter((r) => r.pos === START)).toHaveLength(1);

    // 1...e5 and 1...c5 diverge — one row apiece, each credited to one game.
    const afterE4 = 'rnbqkbnr/pppp1ppp/8/4p3/4P3/8/PPPP1PPP/RNBQKBNR w KQkq -';
    expect(rows.find((r) => r.pos === afterE4 && r.move === 'Nf3'))
      .toEqual({ pos: afterE4, move: 'Nf3', games: 1, white: 1, draws: 0, black: 0 });
  });

  it('a game with no recorded result counts toward games but no side', () => {
    const games = [{ id: 903, result: '*', movetext: null, pgn: '[Result "*"]\n\n1. e4 *' }];
    const rows = computePositions(games);
    const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -';
    expect(rows).toEqual([{ pos: START, move: 'e4', games: 1, white: 0, draws: 0, black: 0 }]);
  });

  it('§6.3 — a game contributes at most once to any position, even by repetition', () => {
    // Knights shuffle back to the start twice; the starting position must be
    // credited once, for whichever move was played the FIRST time.
    const games = [{
      id: 904, result: '1-0', movetext: null,
      pgn: '[Result "1-0"]\n\n1. Nf3 Nf6 2. Ng1 Ng8 3. Nc3 Nc6 1-0'
    }];
    const rows = computePositions(games);
    const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -';
    expect(rows.filter((r) => r.pos === START)).toEqual([
      { pos: START, move: 'Nf3', games: 1, white: 1, draws: 0, black: 0 }
    ]);
  });

  it('an unreadable game is skipped, not fatal to the rest', () => {
    const good = { id: 905, result: '1-0', movetext: null, pgn: '[Result "1-0"]\n\n1. e4 1-0' };
    const bad = { id: 906, result: '1-0', movetext: 'this is not movetext {{{' };
    expect(() => computePositions([bad, good])).not.toThrow();
    const rows = computePositions([bad, good]);
    expect(rows.some((r) => r.move === 'e4')).toBe(true);
  });
});

describe('computePositions — cross-checked against samples/build_positions.py', () => {
  it('agrees with the Python script row-for-row on the same 40-game corpus', () => {
    const jsRows = computePositions(GAMES);
    expect(sorted(jsRows)).toEqual(sorted(pythonRows));
  });

  it('the starting position totals exactly 40 games across every first move', () => {
    const jsRows = computePositions(GAMES);
    const START = 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq -';
    const total = jsRows.filter((r) => r.pos === START).reduce((a, r) => a + r.games, 0);
    expect(total).toBe(GAMES.length);
  });
});
